Repository ilse31/baca-manga, pull requests merged in 2022-10, with the labels that each got.

#1 add readme
  Readme.md
Labels: hacktoberfest accepted

#3 add struct pokedex
  response/Bejjo.go
Labels: hacktoberfest accepted, hacktoberfest

#4 commit by irpansyah
  response/Irfansyah.go
Labels: hacktoberfest accepted, hacktoberfest

#8 commit lagi dari irpan
  response/Irfansyah.go
Labels: hacktoberfest accepted, hacktoberfest

#6 commit by han
  response/itsukahan.go
Labels: hacktoberfest accepted, hacktoberfest

#9 commit from Aleyy
  response/Ale.go
Labels: hacktoberfest accepted, hacktoberfest

#13 commit from ivan: add struct
  controllers/IvanController.go
  response/IvanResponse.go
Labels: hacktoberfest accepted, hacktoberfest

#16 add route pokedex
  routes/routes.go
Labels: hacktoberfest accepted, hacktoberfest

#18 add sp stats
  controllers/BejjoController.go
  response/Bejjo.go
Labels: hacktoberfest accepted, hacktoberfest

#19 controller
  controllers/Itsukacontroller.go
Labels: hacktoberfest accepted, hacktoberfest

#20 willygoid
  response/Willygoid.go
Labels: hacktoberfest accepted, hacktoberfest

#21 commit from ivan: make new struct
  controllers/IvanController.go
  response/IvanResponse.go
Labels: hacktoberfest accepted, hacktoberfest

#22 add new pokemon struct
  controllers/IvanController.go
  response/IvanResponse.go
Labels: hacktoberfest accepted, hacktoberfest

#25 Menambahkan struct VillaneuvoStruct
  response/Villaneuvo.go
Labels: hacktoberfest accepted, hacktoberfest

#26 Ip
  controllers/BejjoController.go
  controllers/ListKomik.go
  response/AdmAlfrizi.go
  response/Ale.go
  response/Bejjo.go
  response/IvanResponse.go
  response/MangaResponses.go
  response/itsukahan.go
Labels: hacktoberfest accepted, hacktoberfest

#27 menambahkan response enricozd
  response/enricozd.go
Labels: hacktoberfest-accepted, hacktoberfest

#28 edit error
  response/enricozd.go
Labels: hacktoberfest-accepted, hacktoberfest

#29 menambah controller enzdController
  controllers/enzdController.go
Labels: hacktoberfest-accepted, hacktoberfest

#30 menambah router
  controllers/enzdController.go
  routes/routes.go
Labels: hacktoberfest-accepted, hacktoberfest

#31 Wagyu a5
  controllers/WagyuController.go
  response/wagyuA5.go
Labels: hacktoberfest-accepted, hacktoberfest

#32 from wagyuA5 edit routes.go
  routes/routes.go
Labels: hacktoberfest-accepted, hacktoberfest

#33 from wahyu delete wagyuError
  response/wagyuA5.go
Labels: hacktoberfest-accepted, hacktoberfest

#34 add controller komik
  controllers/ListKomik.go
Labels: hacktoberfest-accepted, hacktoberfest

#35 New ip
  controllers/MhsController.go
  response/MhsResponses.go
  routes/routes.go
Labels: hacktoberfest-accepted, hacktoberfest

#36 add new controller
  routes/routes.go
Labels: hacktoberfest-accepted, hacktoberfest

#39 [add] new error response at KhoeruError
  response/KhoeruResponse.go
Labels: hacktoberfest-accepted, hacktoberfest

#40 [add] khoeru controller response
  controllers/KhoeruController.go
Labels: hacktoberfest-accepted, hacktoberfest

#43 Create VillaneuvoController.go
  controllers/VillaneuvoController.go
Labels: hacktoberfest-accepted, hacktoberfest

#44 Create Reza Struct
  response/reza.go
Labels: hacktoberfest-accepted, hacktoberfest

#45 Update Route Baca Manga
  routes/routes.go
Labels: hacktoberfest-accepted, hacktoberfest

#46 router
  response/itsukahan.go
  routes/routes.go
Labels: hacktoberfest-accepted, hacktoberfest

#49 [add] description controller and khoeru route
  controllers/KhoeruController.go
  routes/routes.go
Labels: hacktoberfest-accepted, hacktoberfest

#50 AddGenre
  response/itsukahan.go
Labels: hacktoberfest-accepted, hacktoberfest

#51 push-1
  response/Dissleeping.go
Labels: hacktoberfest-accepted, hacktoberfest

#52 push-1
  response/Nurul.go
Labels: hacktoberfest-accepted, hacktoberfest

#53 push-2
  controllers/NurulController.go
Labels: hacktoberfest-accepted, hacktoberfest

#54 push-2
  controllers/DissleepingController.go
Labels: hacktoberfest-accepted, hacktoberfest

#55 push-3
  routes/routes.go
Labels: hacktoberfest-accepted, hacktoberfest

#56 push-3
  routes/routes.go
Labels: hacktoberfest-accepted, hacktoberfest

#57 push-4
  response/Nurul.go
Labels: hacktoberfest-accepted, hacktoberfest

#58 push-4
  response/Dissleeping.go
Labels: hacktoberfest-accepted, hacktoberfest
